### ISSUE TITLE
Našel nekaj bugov

### ISSUE THREAD

**Issue by gigaKosec** [matejmeglic/personal_trainer#1]
- če cache prazen, še vedno ne dela input mealov in ne output mealov (šele ko dobi dummy podatke, deluje. A se to dogaja samo pri meni?)
- po novem se, ko se izvede meal input, posodobi tudi meal output, toda skupaj se dodajajo obroki različih dni, kar ni ok

Bom jaz to popravil (že delam na tem) in poslal pull request, da se dodajo spremembe.

**Comment by matejmeglic** [comment]
1. cache_empty: meni deluje normalno, ful čudno.
2. meal input posodobi meal output za isti dan in meni napiše samo tisti dan. Pls check

**Comment by matejmeglic** [comment]
Žiga, preglej in potestiraj zadnji master in potem javi, če lahko tole consideramo CLOSEd ?

**Comment by gigaKosec** [comment]
Odlično - bom stestiral.

V V tor., 10. dec. 2019 ob 14:56 je oseba Matej Meglic <
notifications@github.com> napisala:

**Comment by gigaKosec** [comment]
Sem stestiral, meni deluje vse ok - omenjenih bugov ni več, novi feature-i
delujejo. Žurka! Consider it closed.


V V tor., 10. dec. 2019 ob 15:34 je oseba Giga Kosec <giga.kosec@gmail.com>
napisala:
